name: attendance_tracker
description: Face recognition based attendance tracking system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  geolocator: ^13.0.2
  table_calendar: ^3.1.3
  intl: ^0.19.0
  http: ^1.1.0
  shared_preferences: ^2.2.2
  jwt_decoder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/SVN-ProductSansRegular.ttf
        - asset: assets/SVN-ProductSansBold.ttf
          weight: 700
        - asset: assets/SVN-ProductSansItalic.ttf
          style: italic