"""Initial migration

Revision ID: 0fa0dca9fa20
Revises: de62f4037b2f
Create Date: 2024-12-17 09:56:19.142464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fa0dca9fa20'
down_revision = 'de62f4037b2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Distance in meters from check point',
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='Record status: SUCCESS, FAILED',
               existing_nullable=True,
               existing_server_default=sa.text("'SUCCESS'::character varying"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance_records', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               comment='Record status: SUCCESS, FAILED',
               existing_nullable=True,
               existing_server_default=sa.text("'SUCCESS'::character varying"))
        batch_op.alter_column('location',
               existing_type=sa.INTEGER(),
               comment='Distance in meters from check point',
               existing_nullable=True)

    # ### end Alembic commands ###
